### ISSUE TITLE
JavaScript interop calls cannot be issued at this time.

### ISSUE THREAD

**Issue by K1vs** [vikramlearning/blazorbootstrap#205]
Hi, I found that when placing some components (eg modal and accordion) inside other components, the following error can be found in the log.

`Microsoft.AspNetCore.Server.Kestrel: Error: Connection id "0HMQL8SRMGJ30", Request id "0HMQL8SRMGJ30:00000001": An unhandled exception was thrown by the application.

System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorBootstrap.Modal.DisposeAsync(Boolean disposing)
   at BlazorBootstrap.Base.BaseAfterRenderComponent.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DisposeAsync()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.<DisposeAsync>g__Await|22_0(Int32 i, ValueTask vt, List`1 toDispose)
   at Microsoft.AspNetCore.Http.Features.RequestServicesFeature.<DisposeAsync>g__Awaited|9_0(RequestServicesFeature servicesFeature, ValueTask vt)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<FireOnCompleted>g__ProcessEvents|242_0(HttpProtocol protocol, Stack`1 events)
The program '[25044] NET7.BlazorServerApp.exe' has exited with code 4294967295 (0xffffffff).`

This does not happen if you place the component on the root page. It is extremely easy to reproduce, in the example for dotnet7 add code to the component, for example SurveyPrompt.
`
<button class="btn btn-primary" @onclick="() => modal.ShowAsync()">Show me</button>

<Modal @ref="modal">
    <BodyTemplate>
        <button class="btn btn-primary" @onclick="() => modal.HideAsync()">Click me</button>
    </BodyTemplate>
</Modal>

@code {
    private Modal? modal;

    // Demonstrates how a parent component can supply parameters
    [Parameter]
    public string? Title { get; set; }
}
`

**Comment by K1vs** [comment]
The problem also exists for .NET 6 Blazor Server.

**Comment by gvreddy04** [comment]
@K1vs Thank you for trying `BlazorBootstrap` components. I'm not able to reproduce this issue in .NET 6 / .NET 7 Blazor Server. If possible, can you share a reproducable GitHub repo.

Othe Details:
 Blazor Bootstrap Version: 
_Host.cshtml file code:

**Comment by K1vs** [comment]
Hi, https://github.com/K1vs/blazorbootstrap-starter-templates/blob/master/src/BlazorBootstrap.Templates.Starter/NET7.BlazorServerApp/Pages/Index.razor this my modification to your project template.
Just start NET7.BlazorServerApp and see Visual Studio debug window.
<img width="1542" alt="image" src="https://github.com/vikramlearning/blazorbootstrap/assets/11088116/4ec4c729-49ba-44ad-b46c-21b29e6794fe">

**Comment by adamshakhabov** [comment]
I have the same issue.
