### ISSUE TITLE
Multiple of the same chart causing js exception

### ISSUE THREAD

**Issue by PotatoDotJar** [vikramlearning/blazorbootstrap#283]
**Describe the bug**
When adding two line charts in a blazor page or component as the documentation shows, a JS exception is thrown. When using just one line chart, there is no error and everything works as intended.
![image](https://github.com/vikramlearning/blazorbootstrap/assets/7833468/cf93562a-e58a-44e2-a4a6-d6990e7ecc2d)

**To Reproduce**
1. Create a Blazor Server project following the "Getting Started" guide for BlazorBootstrap.
2. Create a new Blazor page.
3. Add two line charts to the page with data. (I copied the code from the docs example of the WORM line chart).
4. When loading the page. The following JS exception is thrown and only one chart is rendered, but it is not functional.

```
Uncaught TypeError: Cannot read properties of undefined (reading '_active')
    at Object.beforeDraw (blazor.bootstrap.js:704:39)
    at c (chart.umd.min.js:7:901)
    at Qs._notify (chart.umd.min.js:13:82403)
    at Qs.notify (chart.umd.min.js:13:82224)
    at wn.notifyPlugins (chart.umd.min.js:13:100826)
    at wn.draw (chart.umd.min.js:13:96086)
    at chart.umd.min.js:7:6768
    at Map.forEach (<anonymous>)
    at mt._update (chart.umd.min.js:7:6547)
    at chart.umd.min.js:7:6440
    
[2023-07-13T05:42:45.929Z] Error: Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading '_active')
TypeError: Cannot read properties of undefined (reading '_active')
    at Object.beforeDraw (https://localhost:7062/_content/Blazor.Bootstrap/blazor.bootstrap.js:704:39)
    at c (https://localhost:7062/lib/chartjs/chart.umd.min.js:7:901)
    at Qs._notify (https://localhost:7062/lib/chartjs/chart.umd.min.js:13:82403)
    at Qs.notify (https://localhost:7062/lib/chartjs/chart.umd.min.js:13:82224)
    at wn.notifyPlugins (https://localhost:7062/lib/chartjs/chart.umd.min.js:13:100826)
    at wn.draw (https://localhost:7062/lib/chartjs/chart.umd.min.js:13:96086)
    at wn.render (https://localhost:7062/lib/chartjs/chart.umd.min.js:13:95861)
    at wn.update (https://localhost:7062/lib/chartjs/chart.umd.min.js:13:93945)
    at wn.<anonymous> (https://localhost:7062/lib/chartjs/chart.umd.min.js:13:89580)
    at wn._doResize (https://localhost:7062/lib/chartjs/chart.umd.min.js:7:5335)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorBootstrap.LineChart.UpdateAsync(ChartData chartData, IChartOptions chartOptions)
   at Cyberlake.Dashboard.Pages.Dashboard.RenderLineChart2() in C:\Users\RJ\PersonalGit\CyberlakeDashboard\CyberlakeDashboard\Cyberlake.Dashboard\Pages\Dashboard.razor:line 107
   at Cyberlake.Dashboard.Pages.Dashboard.OnAfterRenderAsync(Boolean firstRender) in C:\Users\RJ\PersonalGit\CyberlakeDashboard\CyberlakeDashboard\Cyberlake.Dashboard\Pages\Dashboard.razor:line 18
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Specifically, here is where the error is thrown:
![image](https://github.com/vikramlearning/blazorbootstrap/assets/7833468/424aef63-86ce-4a02-ae9a-5e53aeb25e7b)

**Expected behavior**
I expect two line charts to render on the page and be functional. Having two line charts on the same Blazor page seems like it would be a common requirement, but I have not been able to find anyone else having this issue.

**Versions (please complete the following information):**
 - BlazorBootstrap: 1.9.4
 - Blazor WebAssembly / Server: Server
 - .NET Version: .NET 7

**Sample code**
Blazor Page Code to reproduce issue:
```razor
@page "/dashboard"
@* @attribute [Authorize] *@

<PageTitle>Dashboard</PageTitle>

<LineChart @ref="lineChart1" Class="md-4"></LineChart>
<LineChart @ref="lineChart2" Class="md-4"></LineChart>

@code {
    private LineChart lineChart1;
    private LineChart lineChart2;
    
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await RenderLineChart1();
        await RenderLineChart2();

        await base.OnAfterRenderAsync(firstRender);
    }

    private async Task RenderLineChart1()
    {
        var data = new ChartData
            {
                Labels = new List<string> { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" },
                Datasets = new List<IChartDataset>()
                {
                    new LineChartDataset()
                    {
                        Label = "India",
                        Data = new List<double>{ 9, 20, 29, 33, 50, 66, 75, 86, 91, 105, 120, 126, 141, 150, 156, 164, 177, 180, 184, 195 },
                        BackgroundColor = new List<string>{ "rgb(88, 80, 141)" },
                        BorderColor = new List<string>{ "rgb(88, 80, 141)" },
                        BorderWidth = new List<double>{2},
                        HoverBorderWidth = new List<double>{4},
                        PointBackgroundColor = new List<string>{ "rgb(88, 80, 141)" },
                        PointBorderColor = new List<string>{ "rgb(88, 80, 141)" },
                        PointRadius = new List<int>{0}, // hide points
                        PointHoverRadius = new List<int>{4},
                    }
                }
            };

        var options = new LineChartOptions();

        //options.Interaction.Mode = InteractionMode.Index;

        options.Plugins.Title.Text = "LineChart1";
        options.Plugins.Title.Display = true;
        options.Plugins.Title.Font.Size = 20;

        options.Responsive = true;

        // options.Scales.X.Title.Text = "Overs";
        // options.Scales.X.Title.Display = true;
        //
        // options.Scales.Y.Title.Text = "Runs";
        // options.Scales.Y.Title.Display = true;

        await lineChart1.UpdateAsync(data, options);
    }
    
    private async Task RenderLineChart2()
    {
        var data = new ChartData
            {
                Labels = new List<string> { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" },
                Datasets = new List<IChartDataset>()
                {
                    new LineChartDataset()
                    {
                        Label = "England",
                        Data = new List<double>{ 1, 1, 8, 19, 24, 26, 39, 47, 56, 66, 75, 88, 95, 100, 109, 114, 124, 129, 140, 142 },
                        BackgroundColor = new List<string>{ "rgb(255, 166, 0)" },
                        BorderColor = new List<string>{ "rgb(255, 166, 0)" },
                        BorderWidth = new List<double>{2},
                        HoverBorderWidth = new List<double>{4},
                        PointBackgroundColor = new List<string>{ "rgb(255, 166, 0)" },
                        PointBorderColor = new List<string>{ "rgb(255, 166, 0)" },
                        PointRadius = new List<int>{0}, // hide points
                        PointHoverRadius = new List<int>{4},                        
                    }
                }
            };

        var options = new LineChartOptions();

        //options.Interaction.Mode = InteractionMode.Index;

        options.Plugins.Title.Text = "LineChart2";
        options.Plugins.Title.Display = true;
        options.Plugins.Title.Font.Size = 20;

        options.Responsive = true;

        // options.Scales.X.Title.Text = "Overs";
        // options.Scales.X.Title.Display = true;
        //
        // options.Scales.Y.Title.Text = "Runs";
        // options.Scales.Y.Title.Display = true;

        await lineChart2.UpdateAsync(data, options);
    }
}
```

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser chrome
 - Version 114.0.5735.199

**Additional context**
I spent a ton of time trying to figure this issue out. I don't think it could be a configuration/setup issue, but there is always that possibility. Looking at the JS for blazorbootstrap, it seems like an instancing issue with the line charts. Normal chart JS should be able to support two line charts on the same page.

**Comment by proteeje** [comment]
I also receive this error when simply adding a button on the same page.

**Comment by PotatoDotJar** [comment]
@proteeje Thank you for you input. Perhaps I can make a work around knowing this.

**Comment by gvreddy04** [comment]
@PotatoDotJar I am not able to reproduce the issue. I am fine with your PR adding a null check.
