### ISSUE TITLE
Modal Throws Error on Navigating Away in .NET 8

### ISSUE THREAD

**Issue by fyiweb** [vikramlearning/blazorbootstrap#465]
**Describe the bug**
In a .NET 8 (Interactive Server, per component) project, when creating a simple page with one of the Modal examples, the modal works properly, but when the user navigates away from page to another page an error is thrown:

```
Error: Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'backdrop')
TypeError: Cannot read properties of undefined (reading 'backdrop')
    at Ni._initializeBackDrop (https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js:6:52074)
    at new Ni (https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js:6:50951)
    at Ni.getOrCreateInstance (https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js:6:8197)
    at Object.dispose (http://localhost:5062/_content/Blazor.Bootstrap/blazor.bootstrap.js:401:31)
    at http://localhost:5062/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://localhost:5062/_framework/blazor.web.js:1:3201)
    at fn._invokeClientMethod (http://localhost:5062/_framework/blazor.web.js:1:62541)
    at fn._processIncomingData (http://localhost:5062/_framework/blazor.web.js:1:60016)
    at connection.onreceive (http://localhost:5062/_framework/blazor.web.js:1:53657)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorBootstrap.Modal.DisposeAsync(Boolean disposing)
   at BlazorBootstrap.BlazorBootstrapComponentBase.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|79_0(Task result)
```

<img width="424" alt="image" src="https://github.com/vikramlearning/blazorbootstrap/assets/4951283/30ebab2d-395b-4060-b658-121e6ee0afeb">

It appears the Modal component is firing a JS Interop to Bootstrap to initialize something during the component's Dispose() but is failing as the object is no longer in the DOM?

This causes a Blazor UI error:

<img width="309" alt="image" src="https://github.com/vikramlearning/blazorbootstrap/assets/4951283/73defa67-e0ae-4546-b894-da529820b419">

**Versions (please complete the following information):**
 - BlazorBootstrap: 1.10.4
 - Blazor WebAssembly / Server: Server
 - .NET Version: .NET 8

**Comment by firstwatch** [comment]
I've had this happen with other components as well: .net 8, interactive server, per page.
