### ISSUE TITLE
Using Toast Service Giving Error

### ISSUE THREAD

**Issue by im-ashar** [vikramlearning/blazorbootstrap#487]
**Describe the bug**
Error: Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'classList')
TypeError: Cannot read properties of undefined (reading 'classList')
    at Pn.isShown (https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js:6:78939)
    at Pn.dispose (https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js:6:78846)
    at Object.dispose (https://localhost:7188/_content/Blazor.Bootstrap/blazor.bootstrap.js:576:88)
    at https://localhost:7188/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7188/_framework/blazor.web.js:1:3201)
    at fn._invokeClientMethod (https://localhost:7188/_framework/blazor.web.js:1:62541)
    at fn._processIncomingData (https://localhost:7188/_framework/blazor.web.js:1:60016)
    at connection.onreceive (https://localhost:7188/_framework/blazor.web.js:1:53657)
    at i.onmessage (https://localhost:7188/_framework/blazor.web.js:1:81802)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorBootstrap.Toast.DisposeAsync(Boolean disposing)
   at BlazorBootstrap.BlazorBootstrapComponentBase.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|79_0(Task result)

**To Reproduce**
1. Use Toast In A Page
2. Go To Another Page using navigation manager.
3. You will get this in console.

**Expected behavior**
It should navigate to the other pages

**Versions (please complete the following information):**
 - BlazorBootstrap: 1.10.4
 - Blazor WebAssembly / Server: Server
 - .NET Version: .Net 8 (Per Page Interactivity)

**Comment by gvreddy04** [comment]
@im-ashar Thank you for trying BlazorBootstrap. Can you please share the sample code to reproduce the issue, using as few steps as possible? This will help us to better understand the problem.
