### ISSUE TITLE
Button click events stop firing after modal is triggered, then closed, and the control is changed

### ISSUE THREAD

**Issue by theSnoMan1** [vikramlearning/blazorbootstrap#489]
Note: See the included diagram which shows my program's layout.

When I trigger the modal on my "Customer List" page to display the "Customer Detail" control and then close it, and then navigate away from the "Customer List" page all buttons in my "App Content" section stop working.  The button I placed on my "inventory" page no longer works either.  Before If I navigate away I can trigger the modal numerous times and the pagination buttons on my list.  If I move away without triggering the modal the button on my "Inventory" page works fine and I can come back to the "Customer List" page and again, all buttons work fine.  So it's any time the modal has been triggered and then you move away from the page.   

The "App Navigation" buttons on the left still work fine and the "Main Navigation" buttons in the header continue to work just fine.  The only thing that restores the buttons in the "App Content" ae is a refresh.  Helpfully this makes sense.

![ProgramLayout](https://github.com/vikramlearning/blazorbootstrap/assets/155317172/65f66bff-af98-47ab-8231-d8c7b69baf09)

The browser shows the following error:
`[2023-12-31T17:15:12.028Z] Error: Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'backdrop')
TypeError: Cannot read properties of undefined (reading 'backdrop')
    at Ni._initializeBackDrop (https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js:6:52074)
    at new Ni (https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js:6:50951)
    at Ni.getOrCreateInstance (https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js:6:8197)
    at Object.dispose (https://localhost:7089/_content/Blazor.Bootstrap/blazor.bootstrap.js:425:31)
    at https://localhost:7089/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7089/_framework/blazor.web.js:1:3201)
    at fn._invokeClientMethod (https://localhost:7089/_framework/blazor.web.js:1:62541)
    at fn._processIncomingData (https://localhost:7089/_framework/blazor.web.js:1:60016)
    at connection.onreceive (https://localhost:7089/_framework/blazor.web.js:1:53657)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorBootstrap.Modal.DisposeAsync(Boolean disposing)
   at BlazorBootstrap.BlazorBootstrapComponentBase.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|79_0(Task result)
log @ blazor.web.js:1
unhandledError @ blazor.web.js:1
(anonymous) @ blazor.web.js:1
_invokeClientMethod @ blazor.web.js:1
_processIncomingData @ blazor.web.js:1
connection.onreceive @ blazor.web.js:1
i.onmessage @ blazor.web.js:1
`

**Comment by gvreddy04** [comment]
@theSnoMan1 Thank you for using **BlazorBootstrap**. Could you please test and let us know your scenario again with version **1.10.5**?

**Comment by theSnoMan1** [comment]
Hi @gvreddy04 , I just updated via npm and ran it and the problem is still there.   I re-did a decent amount of my layout this morning, eliminating the App Layout and replacing with with my Application components.  Basically everything is manualy wired up, not more using the @Body element.  So now I have only the Main Layout which still used the @Body element and forks to the static content and to the Application component.  I then moved the modal up to my new Application component.  What I found was as long as I stayed in the Application all worked fine.  As soon as I navigated away to one of the static pages the problem occurred.   It doesn't matter if the modal is ever triggered or not.  If it's been loaded and you navigate away it throws the error.  I suspect the problem is the DOM element is gone and the JS is still looking for it.  Here is the latest error I captured (not sure if anything changed)....

[2024-01-01T15:32:17.071Z] Error: Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'backdrop')
TypeError: Cannot read properties of undefined (reading 'backdrop')
    at Ni._initializeBackDrop (https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js:6:52074)
    at new Ni (https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js:6:50951)
    at Ni.getOrCreateInstance (https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js:6:8197)
    at Object.dispose (https://localhost:7089/_content/Blazor.Bootstrap/blazor.bootstrap.js:425:31)
    at https://localhost:7089/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7089/_framework/blazor.web.js:1:3201)
    at fn._invokeClientMethod (https://localhost:7089/_framework/blazor.web.js:1:62541)
    at fn._processIncomingData (https://localhost:7089/_framework/blazor.web.js:1:60016)
    at connection.onreceive (https://localhost:7089/_framework/blazor.web.js:1:53657)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorBootstrap.Modal.DisposeAsync(Boolean disposing)
   at BlazorBootstrap.BlazorBootstrapComponentBase.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|79_0(Task result)
log @ blazor.web.js:1

**Comment by theSnoMan1** [comment]
I suspect I could get around this issue by putting the modal in the Main Layout but I'm new to Blazor and don't know how to reference the Layout from the child components.  I attempted last night to use Cascading Value and that didn't work at all.  I'm my new Application component in passing "this" as a parameter to each child it creates but in a layout I don't know how to do that.

**Comment by gvreddy04** [comment]
@theSnoMan1 Can you share the below details:

 - BlazorBootstrap Version: 
 - Blazor WebAssembly / Server: 
 - Render Mode: 
 - Render Location: 
 - .NET Version:

**Comment by theSnoMan1** [comment]
BlazorBootstrap Version: **NuGet says 1.10.5 in the window, in the solution explorer it says 1.10.4 (see pic)**
Blazor WebAssembly / Server: **server only**
Render Mode: **interactiveserver**
Render Location: 
.NET Version: **.NET 8**

Visual Studio: Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.8.3

The site has been run on both the built in debugging server and a publicly available IIS installation with the same results.

Sorry, I'm very new to Blazor and C# for that matter.  I've used VB.net for several years but I mainly do programming for some of my own things and it's not often enough to be truly good at it.  So I hope I answered your questions appropriately.


![image](https://github.com/vikramlearning/blazorbootstrap/assets/155317172/85a31739-2a53-4c91-8608-eac4576948f2)

![image](https://github.com/vikramlearning/blazorbootstrap/assets/155317172/5ecf9f48-b592-43cf-a4b5-c9fb88d217b9)

**Comment by gvreddy04** [comment]
@theSnoMan1 Can you refer the below getting started doc once?

https://docs.blazorbootstrap.com/getting-started/blazor-webapp-server-global-net-8

**Comment by gvreddy04** [comment]
@theSnoMan1 If you are facing issue with the BlazorBootstrap version. Please uninstall and install.

**Comment by theSnoMan1** [comment]
I went ahead and did that and it didn't seem to fix it.  So I published to
IIS and tried it out and it seems to be working fine now.  So I went back
to the built in debug server, cleared the network cache in Chrome and it
appears to be working there now too!  So I don't know if the update to
1.10.5 fixed it or what.

**Comment by gvreddy04** [comment]
@theSnoMan1 Yes, we made some updates in v1.10.5.

**Comment by theSnoMan1** [comment]
Thank you very much for your help. I really appreciate it.  I spent hours
on this issue.
