### ISSUE TITLE
Running the demo program (BlazorBootstrap.Demo.Server) we get a lot errors using auto complete.

### ISSUE THREAD

**Issue by Helge-Tveranger** [vikramlearning/blazorbootstrap#518]
Running seems to work, but we get a lot of errors in the log:

---> (Inner Exception #9) Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
 at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
 at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
 at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
 at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
 at BlazorBootstrap.AutoComplete`1.DisposeAsync(Boolean disposing) in C:\Source\blazorbootstrap\blazorbootstrap\Components\Form\AutoComplete\AutoComplete.razor.cs:line 41
 at BlazorBootstrap.BlazorBootstrapComponentBase.DisposeAsync() in C:\Source\blazorbootstrap\blazorbootstrap\Components\Base\BlazorBootstrapComponentBase.cs:line 79
 at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()<---    
 
And when using the Autocomplete component in another project I'm getting the same errors and the autocomplete component works on the page loading, but as soon as I reaload the page its stops working, since the Crome developer console shows this error:

blazor.server.js:1 Uncaught Error: Found malformed component comment at Blazor: .....

So, for me this component is per time useless.

**Comment by MarvinKlein1508** [comment]
Hi @Helge-Tveranger 

I was curious and tried the sample project myself. It works fine for me in both Blazor Server & WebAssembly.

Could you provide more information or maybe create a small sample repository?

- Which version of .NET are you using?
- Are you using .NET MAUI?
- Which Blazor template (Server/SSR/WebAssembly)
- Which version of this library to you use?

**Comment by gvreddy04** [comment]
@Helge-Tveranger Can you share a screen recording to help us understand better?

**Comment by Helge-Tveranger** [comment]
I see that the net version for the Blazor project itself
is <TargetFramework>net6.0</TargetFramework> and in my project I'm
using <TargetFramework>net8.0</TargetFramework>

And when running the BlazorBootstrap.Demo.Server I'm getting these errors:

[image: image.png]


Regards
Helge


man. 22. jan. 2024 kl. 18:04 skrev Vikram Gaddam ***@***.***>:

**Comment by gvreddy04** [comment]
@Helge-Tveranger Would you mind re-attaching the screenshot? I'd appreciate it.

**Comment by scoroop** [comment]
having the same issue in my project in .net 8 blazor server. 
![image](https://github.com/vikramlearning/blazorbootstrap/assets/18415586/045ca9a3-26ec-4391-8eae-5b984fb429c4)

looks like a very ugly code needs to be added in component dispose - pretty much empty catch 

`async ValueTask IAsyncDisposable.DisposeAsync()
{
    try
    {
        if (objInstance is not null)
        {
            await objInstance.DisposeAsync();
        }
    }
    catch (JSDisconnectedException)
    {
    }
}`

according to couple of threads here and there this seems to be a legit strategy to tackle this issue
https://stackoverflow.com/questions/72488563/blazor-server-side-application-throwing-system-invalidoperationexception-javas

**Comment by gvreddy04** [comment]
@scoroop Thank you so much for sharing the details. I will definitely take a close look.
