### ISSUE TITLE
AutoComplete throws exception

### ISSUE THREAD

**Issue by sanderweltje** [vikramlearning/blazorbootstrap#97]
On a razor page with Autocomplete the following exception is thrown when navigating to a different page

Microsoft.JSInterop.JSException: Failed to execute 'querySelector' on 'Document': '0HMKO40BHF59Q' is not a valid selector.
Error: Failed to execute 'querySelector' on 'Document': '0HMKO40BHF59Q' is not a valid selector.
    at r (https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js:6:813)
    at hi.getInstance (https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js:6:6646)
    at hi.getOrCreateInstance (https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js:6:6713)
    at Object.dispose (http://localhost:5000/_content/Blazor.Bootstrap/blazor.bootstrap.js:52:34)
    at http://localhost:5000/_framework/blazor.server.js:1:3501
    at new Promise (<anonymous>)
    at kt.beginInvokeJSFromDotNet (http://localhost:5000/_framework/blazor.server.js:1:3475)
    at http://localhost:5000/_framework/blazor.server.js:1:72001
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (http://localhost:5000/_framework/blazor.server.js:1:71987)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorBootstrap.AutoComplete`1.DisposeAsync(Boolean disposing)
   at BlazorBootstrap.Base.BaseAfterRenderComponent.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|64_0(Task result)

**Comment by gvreddy04** [comment]
@sanderweltje Can you share the sample project or code to replicate the issue?

Please share the below info:
- Blazor Web Assembly/ Server
- .NET Version

**Comment by sanderweltje** [comment]
I use Blazor Server net6.0 and Blazor.Bootstrap version 0.4.1. I attached a sample project created with VisualStudio 2022
[AutoCompleteException.zip](https://github.com/vikramlearning/blazorbootstrap/files/9591465/AutoCompleteException.zip)

**Comment by sanderweltje** [comment]
Thanks a lot, problem solved.

**Comment by vikneshkumar** [comment]
When I added autocomplete inside the Devexpress grid, I encountered the identical problem. As stated in the previous comment, it works perfectly when I go back to version 0.4.0. I'm currently using version 1.3.1.

https://supportcenter.devexpress.com/ticket/details/t1136877/dxgrid-custom-control-in-dxformlayoutitem-microsoft-jsinterop-jsexception-failed-to
